# Generated by Django 4.2.4 on 2024-08-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
    ]
